% ensure variables are cleared
clearvars;

% ensure src/matlab and subfolders are in the path
filePath = fileparts(which(mfilename));
addpath(genpath(fullfile(filePath, '../../matlab')));

% build configuration
config = BuildRegisterToStandardConfiguration();

pipeline = BuildRegisterToStandardPipeline(config.pathToWorkspace, ...
                                           config.pathToDataset, ...
                                           config.pathToParcellations, ...
                                           config.pathToOutput, ...
                                           config.pathToOutput, ...
                                           config.numSubjects, ...
                                           config);

pipelineExecution = pipeline.run();
