% ensure variables are cleared
clearvars;

% build configuration
parcellation = 'shen_MNI152';
config = BuildSampleConfiguration(parcellation);

pipeline = BuildRegisterParcellationPipeline(config.common.pathToWorkspace, ...
                                             config.common.pathToDataset, ...
                                             config.common.pathToParcellations, ...
                                             config.t1.pathToOutput, ...
                                             config.pipeline2.pathToOutput, ...
                                             config.common.numSubjects, ...
                                             config.pipeline2);
                                           
pipelineExecution = pipeline.run();