% ensure variables are cleared
clearvars;

% build configuration
config = BuildSampleConfiguration();

pipeline = BuildSamplePipeline(config.common.pathToWorkspace, ...
                               config.common.pathToDataset, ...
                               config.pipeline1.pathToOutput, ...
                               config.common.numSubjects, ...
                               config.pipeline1);

pipelineExecution = pipeline.run();