% ensure variables are cleared
clearvars;

% build configuration
config = BuildSampleConfiguration();

pipeline = BuildSegmentationPipeline(config.common.pathToWorkspace, ...
                                     config.common.pathToDataset, ...
                                     config.pipeline1.pathToOutput, ...
                                     config.pipeline3.pathToOutput, ...
                                     config.common.numSubjects, ...
                                     config.pipeline3);
                                   
pipelineExecution = pipeline.run();
