function [sequence] = BuildBrainExtractionSequence(inputs, ...
                                                   subjectName, ...
                                                   pathToWorkspace, ...
                                                   pathToOutput, ...
                                                   config)
%BUILDBRAINEXTRACTIONSEQUENCE Example of a sequence builder for brain extraction.
%   This sequence builder runs brain extraction of a T1w image.
%   
%   Input:
%   - inputs:           Inputs that will be copied into the workspace.
%   - pathToWorkspace:  Path to the sequence's workspace.
%   - pathToOutput:     Path to where we will output the data.
%
%   Output:
%   - sequence:  Built sequence.


%% step 1
% reorient to standard
step1Config = config.step1;
step1Config.inputVolume = sprintf('%s_T1w.nii.gz', subjectName);
step1Config.outputVolume = sprintf('%s_T1w_std.nii.gz', subjectName);
deps1 = { step1Config.inputVolume };
outputs1 = { step1Config.outputVolume };
step1 = Step(@ReorientToStandard, ...
             step1Config, ...
             deps1, ...
             outputs1);

%% step 2
% crop
step2Config = config.step2;
step2Config.inputVolume = step1Config.outputVolume;
step2Config.outputVolume = sprintf('%s_T1w_crop.nii.gz', subjectName);
deps2 = { step2Config.inputVolume };
outputs2 = { step2Config.outputVolume };
step2 = Step(@Crop, ...
             step2Config, ...
             deps2, ...
             outputs2);

%% step 3
% denoise
step3Config = config.step3;
step3Config.inputFile = step2Config.outputVolume;
step3Config.outputFile = sprintf('%s_T1w_denoised.nii', subjectName);
deps3 = { step3Config.inputFile };
outputs3 = { step3Config.outputFile };
step3 = Step(@DenoiseImage, ...
             step3Config, ...
             deps3, ...
             outputs3);

%% step 4
% process anatomical image
step4Config = config.step4;
step4Config.inputFile = step3Config.outputFile;
step4Config.outputFolder = sprintf('%s', subjectName);
deps4 = { step4Config.inputFile };
outputs4 = { ...
  sprintf('%s.anat/T1_biascorr.nii.gz', subjectName), ...
  sprintf('%s.anat/T1_subcort_seg.nii.gz', subjectName), ...
};
step4 = Step(@ProcessAnatomicalImage, ...
             step4Config, ...
             deps4, ...
             outputs4);

%% step 5
% extract brain
step5Config = config.step5;
step5Config.inputVolume = sprintf('%s.anat/T1_biascorr.nii.gz', subjectName);
step5Config.outputVolume = sprintf('%s_T1w_brain.nii.gz', subjectName);
deps5 = { step5Config.inputVolume };
outputs5 = { step5Config.outputVolume };
step5 = Step(@ExtractBrain, ...
             step5Config, ...
             deps5, ...
             outputs5);

%% step 6
% fill holes
step6Config = config.step6;
step6Config.inputVolume = sprintf('%s_T1w_brain_mask.nii.gz', subjectName);
step6Config.outputVolume = sprintf('%s_T1w_brain_mask_filled.nii.gz', subjectName);
deps6 = { step6Config.inputVolume };
outputs6 = { step6Config.outputVolume };
step6 = Step(@FillHoles, ...
             step6Config, ...
             deps6, ...
             outputs6);

%% step 7
% multiply brain by mask
% extra step to be very precise on the extraction
step7Config = config.step7;
step7Config.inputVolume1 = sprintf('%s.anat/T1_biascorr.nii.gz', subjectName);
step7Config.inputVolume2 = sprintf('%s_T1w_brain_mask_filled.nii.gz', subjectName);
step7Config.outputVolume = sprintf('%s_T1w_brain_trim.nii.gz', subjectName);
deps7 = { step7Config.inputVolume1, step7Config.inputVolume2 };
outputs7 = { step7Config.outputVolume };
step7 = Step(@MultiplyVolumes, ...
             step7Config, ...
             deps7, ...
             outputs7);

% set up steps in order
steps = { step1, ...
          step2, ...
          step3, ...
          step4, ...
          step5, ...
          step6, ...
          step7 };

% these files will be copied from the workspace to the output path
outputs = { sprintf('%s_T1w.nii.gz', subjectName)  ...
            sprintf('%s_T1w_brain.nii.gz', subjectName), ...
            sprintf('%s_T1w_brain_mask_filled.nii.gz', subjectName), ...
            sprintf('%s.anat/T1_subcort_seg.nii.gz', subjectName), ...
            sprintf('%s.anat/T1_biascorr.nii.gz', subjectName), ...
            sprintf('%s_T1w_brain_trim.nii.gz', subjectName) };

sequence = Sequence(steps, ...
                    inputs, ...
                    outputs, ...
                    pathToWorkspace, ...
                    pathToOutput, ...
                    config.sequence);

end
