function [sequence] = BuildTransformParcellationSequence(inputs, ...
                                                         parcellation, ...
                                                         subjectName, ...
                                                         pathToWorkspace, ...
                                                         pathToOutput, ...
                                                         config)
%BUILDTRANSFORMPARCELLATIONSEQUENCE Example of a sequence builder.
%   This builder creates a sequence that applies a registration to a given
%   parcellation.
%
%   Input:
%   - inputs:           Inputs that will be copied into the workspace.
%   - pathToWorkspace:  Path to the sequence's workspace.
%   - pathToOutput:     Path to where we will output the data.
%
%   Output:
%   - sequence:  Built sequence.

% get the name of the parcellation w/o the extension
parcellationName = extractBefore(parcellation, '.');

%% step 1
% dilate parcellation
step1Config = config.step1;
step1Config.inputVolume = parcellation;
step1Config.outputVolume = sprintf('%s_dil.nii.gz', parcellationName);
deps1 = { step1Config.inputVolume };
outputs1 = { step1Config.outputVolume };
step1 = Step(@Dilate, ...
             step1Config, ...
             deps1, ...
             outputs1);

%% step 2
% apply inverse warp to parcellation to go down to dof 12
step2Config = config.step2;
% support skipping step 1, so taking the parcellation directly as input
if isfield(config.step1, 'skip') && config.step1.skip
  step2Config.inputVolume = parcellation;
else
  step2Config.inputVolume = step1Config.outputVolume;
end
step2Config.referenceVolume = sprintf('%s_T1w_brain_dof12.nii.gz', ...
                                      subjectName);
step2Config.warpVolume = sprintf('%s_MNI2T1w_warp.nii.gz', subjectName);
step2Config.outputVolume = sprintf('%s_invwarp.nii.gz', parcellationName);
deps2 = { step2Config.inputVolume, ...
          step2Config.referenceVolume,  ...
          step2Config.warpVolume };
outputs2 = { step2Config.outputVolume };
step2 = Step(@ApplyWarp, ...
             step2Config, ...
             deps2, ...
             outputs2);

%% step 3
% apply inverted dof 12 transform to parcellation to go down to dof 6
step3Config = config.step3;
step3Config.inputVolume = step2Config.outputVolume;
step3Config.referenceVolume = sprintf('%s_T1w_brain_dof6.nii.gz', ...
                                      subjectName);
step3Config.initMatrix = sprintf('%s_MNI2T1w_dof12.mat', subjectName);
step3Config.outputVolume = sprintf('%s_invdof12.nii.gz', parcellationName);
deps3 = { step3Config.inputVolume, ...
          step3Config.referenceVolume,  ...
          step3Config.initMatrix };
outputs3 = { step3Config.outputVolume };
step3 = Step(@PerformLinearImageRegistration, ...
             step3Config, ...
             deps3, ...
             outputs3);

%% step 4
% apply inverted dof 6 transform to parcellation to go down to native
step4Config = config.step4;
step4Config.inputVolume = step3Config.outputVolume;
step4Config.referenceVolume = sprintf('%s_T1w_brain_trim.nii.gz', ...
                                      subjectName);
step4Config.initMatrix = sprintf('%s_MNI2T1w_dof6.mat', subjectName);
step4Config.outputVolume = sprintf('%s_%s.nii.gz', ...
                                   parcellationName, ...
                                   subjectName);
deps4 = { step4Config.inputVolume, ...
          step4Config.referenceVolume,  ...
          step4Config.initMatrix };
outputs4 = { step4Config.outputVolume };
step4 = Step(@PerformLinearImageRegistration, ...
             step4Config, ...
             deps4, ...
             outputs4);


%% prepare the sequence
% set up steps in order
steps = { step1, ...
          step2, ...
          step3, ...
          step4 };

% these files will be copied from the workspace to the output path
outputs = { step4Config.outputVolume }; % registered parcellation

sequence = Sequence(steps, ...
                    inputs, ...
                    outputs, ...
                    pathToWorkspace, ...
                    pathToOutput, ...
                    config.sequence);

end
