name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v4

      - name: Set tag
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        id: set-tag
        run: |
          REPOSITORY=$(echo '${{ github.repository }}')
          TAG=$(echo '${{ steps.release.outputs.tag_name }}')
          JSON=$(jq -c --null-input --arg repository "$REPOSITORY" --arg tag "$TAG" '{"repository": $repository, "tag": $tag}')
          echo "json=$JSON" >> $GITHUB_OUTPUT
