# Automate releases of new app versions
name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  # needed for the auto-tag
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          release-type: node

      - uses: actions/checkout@v4

      # put created tag in an env variable to be sent to the dispatch
      - name: Set tag
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        id: set-tag
        run: |
          REPOSITORY=$(echo '${{ github.repository }}')
          TAG=$(echo '${{ steps.release.outputs.tag_name }}')
          JSON=$(jq -c --null-input --arg repository "$REPOSITORY" --arg tag "$TAG" '{"repository": $repository, "tag": $tag}')
          echo "json=$JSON" >> $GITHUB_OUTPUT
